# Generated by Django 6.1 on 2026-08-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial Property')], max_length=50)),
                ('plot_number', models.CharField(blank=True, max_length=50)),
                ('land_size', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('description', models.TextField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.estate')),
            ],
        ),
    ]
