# Generated by Django 6.1 on 2026-08-10 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('skill', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other')], max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='job_applications/id_documents/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='job_applications/cv/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('contacted', 'Contacted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='properties.job')),
            ],
        ),
    ]
