# Generated by Django 6.1 on 2026-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
