# Generated by Django 6.1 on 2026-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkilledWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('skill', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('services', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='skilled_workers/profiles/')),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other')], max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='skilled_workers/id_documents/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='skilled_workers/cv/')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
