# Generated by Django 6.1 on 2026-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_customer_notes_remove_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='customer_ids/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's Licence"), ('passport', 'International Passport'), ('voters_card', "Voter's Card")], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
