# Generated by Django 6.1 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_skilledworker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerhire',
            name='status',
            field=models.CharField(choices=[('requested', 'Pending'), ('active', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
