# Generated by Django 6.1 on 2026-08-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_workerhire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerreview',
            name='hire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_review', to='properties.workerhire'),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to='properties.workerhire')),
            ],
        ),
    ]
