# Generated by Django 6.1 on 2026-08-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_marketplaceaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceaccount',
            name='account_type',
        ),
        migrations.AddField(
            model_name='estate',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='digital_layout',
            field=models.FileField(blank=True, null=True, upload_to='estates/layouts/'),
        ),
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='estates/'),
        ),
        migrations.AddField(
            model_name='estate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=100)),
                ('what_comes_with_it', models.TextField(blank=True)),
                ('proposed_company_plan', models.FileField(blank=True, null=True, upload_to='estates/company_plans/')),
                ('digital_layout', models.FileField(blank=True, null=True, upload_to='estates/type_layouts/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='estates/types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_types', to='properties.estate')),
            ],
            options={
                'ordering': ['estate', 'name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='estate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.estatetype'),
        ),
        migrations.CreateModel(
            name='EstateTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estates/types/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.estatetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='estatetype',
            constraint=models.UniqueConstraint(fields=('estate', 'name'), name='unique_estate_type_name'),
        ),
    ]
