# Generated by Django 6.1 on 2026-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_marketplaceaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='development_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='development_plan',
            field=models.FileField(blank=True, null=True, upload_to='estates/development_plans/'),
        ),
        migrations.AddField(
            model_name='estate',
            name='development_plan_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
