# Generated by Django 6.1 on 2026-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Verification Submitted'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='not_submitted', max_length=20),
        ),
    ]
