# Generated by Django 6.1 on 2026-08-20 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_customer_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's Licence"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other')], default='', max_length=50)),
                ('id_number', models.CharField(blank=True, default='', max_length=100)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='account_verification/id_documents/')),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Verification Submitted'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='not_submitted', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
