# Generated by Django 6.1 on 2026-08-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_accountverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='skilledworker',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='skilledworker',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='skilledworker',
            name='id_type',
        ),
    ]
