# Generated by Django 6.1 on 2026-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_remove_customer_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='customer_ids/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's Licence"), ('passport', 'International Passport'), ('voters_card', "Voter's Card")], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skilledworker',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='skilled_workers/id_documents/'),
        ),
        migrations.AddField(
            model_name='skilledworker',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skilledworker',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AccountVerification',
        ),
    ]
