# Generated by Django 6.1 on 2026-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_customer_id_document_customer_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelisting',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='approval_status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='chats_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
