# Generated by Django 6.1 on 2026-08-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_remove_marketplacelisting_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacereview',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_seller_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='properties.marketplacelisting'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
