# Generated by Django 6.1 on 2026-08-25 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_marketplacereview_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacereview',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MarketplaceListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='properties.marketplacelisting')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'viewer'), name='unique_listing_view_per_user')],
            },
        ),
    ]
