# Generated by Django 6.1 on 2026-08-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_alter_marketplacereview_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.marketplacelisting')),
            ],
        ),
        migrations.DeleteModel(
            name='MarketplaceImage',
        ),
    ]
