# Generated by Django 6.1 on 2026-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_marketplacelistingimage_delete_marketplaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('fair', 'Fair')], max_length=30),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiable', 'Negotiable'), ('contact', 'Contact Seller')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='specific_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='whatsapp_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
