# Generated by Django 6.1 on 2026-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_marketplacelisting_brand_marketplacelisting_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_verified',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skilledworker',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
