# Generated by Django 6.1 on 2026-09-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_workermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hire_request', 'Hire Request'), ('hire_accepted', 'Hire Accepted'), ('hire_declined', 'Hire Declined'), ('hire_cancelled', 'Hire Cancelled'), ('worker_message', 'Worker Message'), ('customer_message', 'Customer Message'), ('review', 'Review'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('marketplace_message', 'Marketplace Message')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
