# Generated by Django 6.1 on 2026-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('hire_request', 'Hire Request'), ('hire_accepted', 'Hire Accepted'), ('hire_declined', 'Hire Declined'), ('hire_cancelled', 'Hire Cancelled'), ('worker_message', 'Worker Message'), ('customer_message', 'Customer Message'), ('review', 'Review'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('marketplace_message', 'Marketplace Message'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('job_completed', 'Job Completed')], max_length=50),
        ),
    ]
