# Generated by Django 6.1 on 2026-09-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_marketplace_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workermessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_worker_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraud / Scam'), ('harassment', 'Harassment or Abuse'), ('fake_profile', 'Fake Profile'), ('misleading', 'Misleading Information'), ('inappropriate', 'Inappropriate Behaviour'), ('spam', 'Spam'), ('unsafe', 'Safety Concern'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
