# Generated by Django 6.1 on 2026-09-03 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_marketplacemessage_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerhire',
            name='conversation_deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_worker_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
