# Generated by Django 6.1 on 2026-09-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_workerhire_conversation_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceConversationDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_deletions', to='properties.marketplacelisting')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_conversations_deleted_by_others', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_marketplace_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'user', 'other_user'), name='unique_marketplace_conversation_deletion')],
            },
        ),
    ]
